services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql

  debezium-connect:
    image: debezium/connect:2.1
    container_name: debezium-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - sqlserver
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  debezium-ui:
    image: debezium/debezium-ui:2.1   # THAY ĐỔI Ở ĐÂY: từ "latest" thành "2.1"
    container_name: debezium-ui
    ports:
      - "8084:8080"
    depends_on:
      - debezium-connect
    environment:
      KAFKA_CONNECT_URIS: "http://debezium-connect:8083"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spark-master:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-master
    ports:
      - "8888:8888" # Jupyter Notebook
      - "4040:4040" # Spark UI
    volumes:
      - ./spark_apps:/home/jovyan/work
      - ./spark_jars:/home/jovyan/.ivy2
      
# # --- DỊCH VỤ MỚI ---
#   postgres-metastore:
#     image: postgres:13
#     container_name: postgres-metastore
#     environment:
#       POSTGRES_DB: metastore
#       POSTGRES_USER: hive
#       POSTGRES_PASSWORD: hivepassword
#     volumes:
#       - postgres_metastore_data:/var/lib/postgresql/data

#   hive-metastore:
#     image: bitnami/hive:3 # <-- SỬA IMAGE TẠI ĐÂY
#     container_name: hive-metastore
#     depends_on:
#       - postgres-metastore
#     ports:
#       - "9083:9083"
#     environment: # <-- SỬA LẠI TOÀN BỘ KHỐI NÀY
#       - HIVE_DATABASE_TYPE=postgresql
#       - HIVE_METASTORE_DATABASE_HOST=postgres-metastore
#       - HIVE_METASTORE_DATABASE_NAME=metastore
#       - HIVE_METASTORE_DATABASE_USER=hive
#       - HIVE_METASTORE_DATABASE_PASSWORD=hivepassword
      

#   trino-coordinator:
#     image: trinodb/trino:latest
#     container_name: trino-coordinator
#     depends_on: # Trino cần chờ Metastore khởi động
#       - hive-metastore
#     ports:
#       - "8090:8080"
#     volumes:
#       - ./trino/etc:/etc/trino
# ... (thêm vào cuối tệp docker-compose.yml)
      
  streamlit:
    build: ./streamlit_app
    container_name: streamlit-dashboard
    ports:
      - "8501:8501"
    volumes: # <-- THÊM DÒNG NÀY
    - ./streamlit_app:/app # <-- VÀ DÒNG NÀY
    - ./spark_jars:/home/jovyan/.ivy2
    depends_on:
      - minio
      - spark-master
volumes:
  sqlserver_data:
  minio_data:
  # postgres_metastore_data: # Thêm volume mới
